Repository coding-union-kr/siltarae-fe, pull requests merged in 2023-12, with the labels that each got.

#3 ESLint, Prettier 설정 개선 및 yarn berry 호환성 문제 해결
  .eslintrc.json
  .gitignore
  .pnp.cjs
  .pnp.loader.mjs
  .prettierrc
  .vscode/extensions.json
  .vscode/settings.json
  .yarn/sdks/eslint/bin/eslint.js
  .yarn/sdks/eslint/lib/api.js
  .yarn/sdks/eslint/lib/unsupported-api.js
  .yarn/sdks/eslint/package.json
  .yarn/sdks/integrations.yml
  .yarn/sdks/typescript/bin/tsc
  .yarn/sdks/typescript/bin/tsserver
  .yarn/sdks/typescript/lib/tsc.js
  .yarn/sdks/typescript/lib/tsserver.js
  .yarn/sdks/typescript/lib/tsserverlibrary.js
  .yarn/sdks/typescript/lib/typescript.js
  .yarn/sdks/typescript/package.json
  .yarnrc.yml
  package-lock.json
  package.json
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/api/hello.ts
  src/pages/index.tsx
  yarn.lock
Labels: ⚙️ Setting, 🔥 IMPORTANT

#18 [Setting] 버그이슈 템플릿 수정
  .github/ISSUE_TEMPLATE/버그-리포트-이슈-템플릿.md
Labels: 📄 Docs

#16 [Setting] 초기세팅 추가 부분 수정
  .pnp.cjs
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/index.tsx
  styles/globals.css
  tailwind.config.ts
  yarn.lock
Labels: ⭐️ Feature, ⚙️ Setting

#19 [Feat] Avatar, ProfileAvatar 구현
  .eslintrc.json
  .pnp.cjs
  components/Avatar.tsx
  components/ProfileAvatar.tsx
  next.config.js
  package.json
  pages/_document.tsx
  pages/api/hello.ts
  pages/index.tsx
  tailwind.config.ts
  yarn.lock
Labels: ⭐️ Feature

#20 [Feat] ContentCard 구현
  components/Avatar.tsx
  components/ContentCard.tsx
  components/ProfileAvatar.tsx
  pages/index.tsx
  styles/globals.css
Labels: ⭐️ Feature

#21 [Feat] header 컴포넌트 구현
  components/header.tsx
Labels: ⭐️ Feature, Size: S

#22 [Feat] NavBar 컴포넌트 구현
  components/navBar.tsx
Labels: ⭐️ Feature, Size: S

#24 [Feat] Comment 구현 완료
  components/Comment.tsx
  pages/index.tsx
Labels: ⭐️ Feature

#27 [Feat] Tag 컴포넌트 구현
  components/Tag.tsx
Labels: ⭐️ Feature, Size: S

#28 [Feat] Tag 컴포넌트 삭제기능 추가
  components/Tag.tsx
  pages/index.tsx
Labels: ⭐️ Feature

#29 [Chore] 파일명 Pascal case 로 변경
  components/Header.tsx
  components/NavBar.tsx
Labels: 🐛 Bug, 🔥 IMPORTANT

#30 [Docs] PR 템플릿 추가
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📄 Docs

#31 [Docs] 기능개발-이슈-템플릿.md
  .github/ISSUE_TEMPLATE/기능개발-이슈-템플릿.md
Labels: 📄 Docs

#32 [Docs] 버그-리포트-이슈-템플릿.md 변경
  .github/ISSUE_TEMPLATE/버그-리포트-이슈-템플릿.md
Labels: 📄 Docs

#34 [Feat] TagListItem 컴포넌트 구현
  components/Header.tsx
  components/TagListItem.tsx
  components/header.tsx
Labels: ⭐️ Feature

#33 [Feat] 레이아웃 구현
  layout/Layout.tsx
  pages/_app.tsx
  pages/_document.tsx
  pages/index.tsx
  tailwind.config.ts
Labels: ⭐️ Feature

#44 [Feat] Layout 컴포넌트에 Header, NavBar 컴포넌트 추가
  components/Layout.tsx
  components/NavBar.tsx
Labels: ⭐️ Feature

#45 [Feat] detailedMistakeFeed 페이지 구현
  components/Avatar.tsx
  components/Comment.tsx
  components/CommentInput.tsx
  components/ContentPage.tsx
  components/Header.tsx
  components/NavBar.tsx
  components/ProfileAvatar.tsx
  components/Tag.tsx
  pages/detailedMistakeFeed/index.tsx
Labels: ⭐️ Feature, Size: M

#46 [Bug] Layout 디렉토리 삭제
  layout/Layout.tsx
Labels: 🐛 Bug

#47 [Feat] personalMistake 페이지 구현
  components/AddPostButton.tsx
  components/ContentCard.tsx
  components/Header.tsx
  components/Layout.tsx
  components/NavBar.tsx
  pages/personalMistake/index.tsx
Labels: ⭐️ Feature

#48 [Feat] mistakeFeed 페이지 구현
  components/Avatar.tsx
  components/ContentCard.tsx
  components/Header.tsx
  components/Layout.tsx
  components/NavBar.tsx
  components/ProfileAvatar.tsx
  pages/_app.tsx
  pages/mistakeFeed/index.tsx
  tailwind.config.ts
Labels: ⭐️ Feature

#49 [Feat] myPage 구현
  pages/mistakeFeed/index.tsx
  pages/myPage/index.tsx
  tailwind.config.ts
Labels: ⭐️ Feature

#50 [Feat] TagList페이지 구현
  components/Header.tsx
  components/Layout.tsx
  components/Tag.tsx
  pages/personalMistake/index.tsx
  pages/tagList/index.tsx
Labels: ⭐️ Feature

#51 [Feat] RegisterModal 컴포넌트 구현
  components/RegisterModal.tsx
Labels: ⭐️ Feature

#52 [Feat] socialLoginModal 컴포넌트 구현
  components/SocialLoginModal.tsx
  pages/mistakeFeed/index.tsx
Labels: ⭐️ Feature

#54 [ Refactor] 컴포넌트, 페이지 완성 후 CSS 비율 조정 & 수정
  components/Comment.tsx
  components/ContentPage.tsx
  components/Layout.tsx
  components/NavBar.tsx
  pages/detailedMistakeFeed/index.tsx
  pages/myPage/index.tsx
  pages/personalMistake/index.tsx
Labels: 💊 Refactor

#55 [Feat] SortButton 구현
  components/Avatar.tsx
  components/ProfileAvatar.tsx
  components/SortButton.tsx
  pages/mistakeFeed/index.tsx
Labels: ⭐️ Feature, 💊 Refactor

#58 [Feat] 페이지 라우터 완성 & AddPost 모달 기능 구현
  components/AddPostButton.tsx
  components/ContentCard.tsx
  components/Layout.tsx
  components/PostHeader.tsx
  components/RegisterModal.tsx
  pages/detailedMistakeFeed/index.tsx
  pages/index.tsx
  pages/mistakeFeed/index.tsx
  pages/personalMistake/index.tsx
Labels: ⭐️ Feature

#61 [Feat] API 연결 초기세팅
  api/api.ts
  pages/_app.tsx
  pages/index.tsx
Labels: ⚙️ Setting

#65 [Feat] 좋아요 버튼 컴포넌트 구현
  .pnp.cjs
  components/ContentCard.tsx
  components/LikeButton.tsx
  package.json
  pages/index.tsx
  yarn.lock
Labels: ⭐️ Feature

#70 [Feat] 태그 관련 API 연결
  README.md
  api/mistakeApi.ts
  api/tagApi.ts
  components/ContentCard.tsx
  components/ContentPage.tsx
  components/LikeButton.tsx
  components/RegisterPostModal.tsx
  components/SocialLoginModal.tsx
  components/Tag.tsx
  pages/index.tsx
  pages/personalMistake/index.tsx
  pages/tagList/index.tsx
Labels: ⭐️ Feature

#76 [Feat] 태그생성 기능 구현 및 임시 로그인 토큰 환경변수 설정
  README.md
  api/api.ts
  api/mistakeApi.ts
  api/tagApi.ts
  components/ProfileAvatar.tsx
  components/RegisterPostModal.tsx
  pages/index.tsx
Labels: ⭐️ Feature, 💊 Refactor

#75 [Feat] 임시 리드미 업데이트
  README.md
Labels: 📄 Docs

#77 [Refactor] Link 컴포넌트 위치 변경 및 memberName 값 추가
  README.md
  components/ContentCard.tsx
  components/ContentPage.tsx
  pages/index.tsx
  pages/personalMistake/index.tsx
Labels: 💊 Refactor
