Repository coding-union-kr/siltarae-fe, pull requests merged in 2024-02, with the labels that each got.

#109 Deploy 배포 스크립트를 수정하였어요
  .dockerignore
  .github/workflows/DockerImage.yml
  Dockerfile
Labels: 🛜 Deploy

#111 [Feat] 프로필 이미지 모든 페이지 API 연동
  api/tagApi.ts
  components/CommentInput.tsx
  components/ContentCard.tsx
  components/ContentPage.tsx
  pages/index.tsx
Labels: ⭐️ Feature

#113 [Fix] 미로그인시 로그인창 팝업 위치 수정
  components/SocialLoginModal.tsx
  pages/index.tsx
  pages/myPage/index.tsx
  pages/personalMistake/index.tsx
Labels: 💊 Refactor

#114 [Chore] NavBar CSS 수정
  components/NavBar.tsx
Labels: 💊 Refactor, Size: S

#115 [Chore] env.prodution 추가
  .gitignore
Labels: ⭐️ Feature

#116 [Fix] router 경로 수정
  components/SocialLoginModal.tsx
Labels: 💊 Refactor

#117 deploy: 빌드스크립트 수정
  .github/workflows/DockerImage.yml
  Dockerfile
Labels: 🛜 Deploy

#120 [Refactor] 1차 배포 후 요청사항 수정
  api/authApi.ts
  components/Comment.tsx
  components/ContentPage.tsx
  components/Header.tsx
  components/Layout.tsx
  components/PostHeader.tsx
  components/RegisterPostModal.tsx
  pages/detailedMistakeFeed/[id]/index.tsx
  pages/index.tsx
  pages/myPage/index.tsx
  pages/personalMistake/index.tsx
Labels: 💊 Refactor

#121 [Refactor] CSS 오류 2차 수정
  components/Comment.tsx
  components/CommentInput.tsx
  components/ContentPage.tsx
  pages/tagList/index.tsx
Labels: 💊 Refactor

#123 [Feat] 로그아웃 기능 구현
  api/authApi.ts
  api/userApi.ts
  components/Comment.tsx
  components/ContentPage.tsx
  pages/googlelogin/index.tsx
  pages/myPage/index.tsx
  util/cookie.tsx
Labels: ⭐️ Feature
