Repository coding-union-kr/siltarae-fe, pull requests merged in 2024-01, with the labels that each got.

#85 [Feat] 댓글 api 기능 연결
  api/commentApi.ts
  components/Comment.tsx
  components/CommentInput.tsx
  pages/detailedMistakeFeed/[id]/index.tsx
  pages/index.tsx
Labels: ⭐️ Feature, Size: M

#88 [Fix] Axios Post 구성객체 에러해결 및 headers 디폴트 세팅
  api/api.ts
  api/mistakeApi.ts
  api/tagApi.ts
  api/userApi.ts
  components/ContentCard.tsx
  components/RegisterPostModal.tsx
  pages/index.tsx
Labels: 🐛 Bug, 💊 Refactor

#89 [Fix] 스크롤바 너비 생성으로 인해 전체 Width값 변화로 인한 레이아웃 오류 수정
  components/Header.tsx
  components/NavBar.tsx
  styles/globals.css
Labels: 🐛 Bug, 🔥 IMPORTANT

#94 [Feat] 새로운 태그 추가 기능 및 좋아요 버튼 업데이트
  api/tagApi.ts
  components/ContentCard.tsx
  components/ContentPage.tsx
  components/LikeButton.tsx
  components/RegisterPostModal.tsx
  components/Tag.tsx
  pages/index.tsx
  pages/personalMistake/index.tsx
  pages/tagList/index.tsx
Labels: 🐛 Bug, ⭐️ Feature

#95 [Feat] Oauth 구글 로그인 기능 구현
  .gitignore
  .pnp.cjs
  components/ContentCard.tsx
  components/ContentPage.tsx
  components/SocialLoginModal.tsx
  next.config.js
  package.json
  pages/_app.tsx
  pages/googleLoading/index.tsx
  pages/index.tsx
  store/store.ts
  store/userReducer.tsx
  yarn.lock
Labels: ⭐️ Feature, 🔥 IMPORTANT

#98 [Fix] 구글 로그인 Oauth2 복구
  components/SocialLoginModal.tsx
  pages/googlelogin/index.tsx
  pages/index.tsx
Labels: ⭐️ Feature, 🔥 IMPORTANT

#100 [Feat] 파비콘 & 타이틀 추가
  components/Layout.tsx
  components/Seo.tsx
  public/favicon.ico
Labels: ⭐️ Feature

#105 [Feat] Google 로그인 구현
  .gitignore
  .pnp.cjs
  api/api.ts
  api/authApi.ts
  components/AddPostButton.tsx
  components/ContentCard.tsx
  components/PostHeader.tsx
  components/SocialLoginModal.tsx
  features/auth/authReducer.tsx
  package.json
  pages/googlelogin/index.tsx
  pages/index.tsx
  store/store.ts
  store/userReducer.tsx
  yarn.lock
Labels: ⭐️ Feature

#106 [Feat] 피드 삭제 API 연결, Dropdown 컴포넌트 구현
  api/mistakeApi.ts
  components/Dropdown.tsx
  components/Layout.tsx
  components/PostHeader.tsx
  pages/detailedMistakeFeed/[id]/index.tsx
Labels: ⭐️ Feature

#107 [Fix] 잘못 머지된 커밋 수정
  api/commentApi.ts
  components/PostHeader.tsx
Labels: 🐛 Bug

#108 [Feat] 무한 스크롤 구현
  .pnp.cjs
  components/ContentCard.tsx
  package.json
  pages/index.tsx
  yarn.lock
Labels: ⭐️ Feature
